### ISSUE TITLE
`np.bool` dropped in numpy version 1.24

### ISSUE THREAD

**Issue by Zoophobus** [brightway-lca/brightway2-data#117]
Okay, this is an annoying but gratefully simple issue. The guys behind numpy have just released version 1.24 and in this version they've dropped numpy.bool. So on new installs all references to numpy.bool break, this should probably be reverted to use the standard library version, but in the mean time we (the guys over at the Activity Browser) are just pegging the numpy version to 1.23.5.

**Comment by marc-vdm** [comment]
@cmutel, I wanted to start fixing this, but it seems this repo is not up to date (latest tag is `3.6.1` while the latest conda version is `3.6.5` and no `np.bool` is used anywhere). 

Where can we find the repo, or what do I understand wrong here?

**Comment by michaelweinold** [comment]
> ...it seems this repo is not up to date (latest tag is `3.6.1` while the latest conda version is `3.6.5` and no `np.bool` is used anywhere).

It seems the [GitHub release tags for `bw2data`](https://github.com/brightway-lca/brightway2-data/tags), and the [PyPi version](https://anaconda.org/conda-forge/bw2data/files) (on which [the conda-forge release](https://anaconda.org/conda-forge/bw2data/files) [is based](https://github.com/conda-forge/bw2data-feedstock/blob/main/recipe/meta.yaml)) are out of sync.

@cmutel, can you add the proper release tags to the GitHub repository?

**Comment by cmutel** [comment]
I added the tag `3.6.5` to the [latest commit](https://github.com/brightway-lca/brightway2-data/commit/6c82bf0ced3e84542e0a4b2cbb76dd589fc0a616) which already had the commit message `3.6.5` (make sure you are working on the `legacy` branch). Hope this makes everyone happy, the systematic use of tags is a new thing for Brightway and so there shouldn't be an expectation that they will appear across all libraries and branches.

**Comment by marc-vdm** [comment]
Are you still taking PRs to the legacy branch? 

Without either fixing `numpy=1.23.5` or replacing `np.bool` with `bool` Brightway2 is unuseable (out of the box at least). It's no hassle for me to make the PR, just one question:

Should I then also bump the tag to `3.6.6` and would that work with Brightway2, or would I need to make changes there too?
Just occured to me: I don't have write permissions, so I don't even know if I can bump tags, perhaps @michaelweinold would need to do that.

**Comment by cmutel** [comment]
> Are you still taking PRs to the legacy branch?

Yes, of course, and still making 3.X releases.

> Should I then also bump the tag to 3.6.6

No, but I can add the 3.6.6 tag; you should change the `version` in `__init__.py`, and we will also make a new release of `brightway2` on pypi and anaconda.

**Comment by cmutel** [comment]
Fixed in 3.6.6 release

**Comment by massimopizzol** [comment]
Just tried a fresh installation of bw2 using instructions from website (MacOs) `conda create -n bw -c cmutel -c conda-forge brightway2_nosolver jupyterlab scikit-umfpack` 
After install when doing `import brightway2 as bw`  got the np.bool error. Found this page, downgraded the environement numpy with `conda install numpy=1.23.5.` and problem was solved. It's weird that one gets an error immediately after a fresh install. Would be good to flag this on the main bw page or change the installation line so it specifies directly the right numpy version for the environment - in my experience other less python-savvy users might not solve this so easily.

**Comment by marc-vdm** [comment]
The install instructions for brightway 2 environments are currently broken according to one of our users (https://github.com/LCA-ActivityBrowser/activity-browser/issues/1232)

`conda create -n ENV_NAME -c conda-forge brightway2=2.4` did still work last time I tried.

**Comment by michaelweinold** [comment]
@massimopizzol, you're right - it does seem that this has not been resolved (but I found out what the issue is 🔮✨)

Installing the environment according to your conda command, we end up with the `3.6.5` version of `bw2data` (where the `np.bool` data type [is still present](https://github.com/brightway-lca/brightway2-data/blob/6c82bf0ced3e84542e0a4b2cbb76dd589fc0a616/bw2data/data_store.py#L172)): [`deptree.txt`](https://github.com/brightway-lca/brightway2-data/files/14295603/deptree.txt)

This is odd, because the [`requirements.txt`](https://github.com/brightway-lca/brightway2/blob/master/requirements.txt) of the `brightway2` metapackage does not specify a version. The [`recipe.yaml`](https://github.com/cmutel/brightway2-feedstock/blob/e03d0d0c75afc0fbde253a55988c58a6dce50dcd/recipe/meta.yaml#L27) of the conda feedstock __does__ pin `bw2data` to `3.6.6`...

...except this new recipe did not make it into the conda repository. My guess is that the auto-build failed.

So all that @cmutel needs to do is to trigger the conda build - then we're good!

**Comment by PGjedde** [comment]
Hi bright people, I am the AB user who couldn't install. Thank you for looking into it :)
